### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by dimakuv**
Includes:
- Remove `gramine_ubuntu22.04.patch` since latest Gramine now uses Glibc
  2.35 and experiences no problems on Ubuntu 22.04
- Generate symlink `/dev/sgx/enclave` as a step in `new_init`

Signed-off-by: Dmitrii Kuvaiskii <dmitrii.kuvaiskii@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)

### CODE REVIEW

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`initramfs_builder/new_init` line 6 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-N6wqYgu7bKURrqJU5Uc:-N6wqYgu7bKURrqJU5Ud:bbpk8r0) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/7497f61776b032b4cd67a8721f999c7b5e4e8983/initramfs_builder/new_init#L6)):*
> ```
> 
> mkdir -p /dev/sgx/
> ln -s /dev/sgx_enclave /dev/sgx/enclave || true
> ```

This is a bad hack...
Why can't we handle this uniformly in core Gramine?

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`initramfs_builder/new_init` line 6 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-N6wqYgu7bKURrqJU5Uc:-N88tc8C-7hZKPEJxwzJ:b-dw9o4y) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/7497f61776b032b4cd67a8721f999c7b5e4e8983/initramfs_builder/new_init#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did I even need to do this? I already forgot.

I'll need to test again and remind myself why I needed this. Probably can just remove it.
</blockquote></details>

https://github.com/gramineproject/device-testing-tools/issues/2#issuecomment-1160454107

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: 2 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFhXDWZEbflJyqZSy-F:-NFhXDWZEbflJyqZSy-G:b-og1x9x) (no related file):*
FYI: Revived this PR. Required for https://github.com/gramineproject/gramine/pull/671

___
___
*[`initramfs_builder/new_init` line 6 at r1](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-N6wqYgu7bKURrqJU5Uc:-NFhNlZDEWyxLD2YRwNX:b-6hfl0c) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/7497f61776b032b4cd67a8721f999c7b5e4e8983/initramfs_builder/new_init#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

https://github.com/gramineproject/device-testing-tools/issues/2#issuecomment-1160454107
</blockquote></details>

Done. Removed this hack.

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 4 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFibCok-9FitTl_EWmm:-NFibCok-9FitTl_EWmn:b-3hc7wd) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/gramine_test_dev_ioctl.h#L4)):*
> ```objc
> 
> #ifdef __KERNEL__
> #include <linux/ioctl.h>
> ```

We need this header also in userspace.
___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 6 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFibGXUAnuZz7jhGK2g:-NFibGXUAnuZz7jhGK2h:bv0yete) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/gramine_test_dev_ioctl.h#L6)):*
> ```objc
> #include <linux/ioctl.h>
> #else
> #define __user
> ```

Please wrap in `ifndef`
___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 7 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFibK9XEutX3ItJPAu_:-NFibK9XEutX3ItJPAua:bchk8rw) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/gramine_test_dev_ioctl.h#L7)):*
> ```objc
> #else
> #define __user
> #define loff_t ssize_t
> ```

`typedef` or better `include <sys/types.h>`
___
*[`gramine-device-testing-module/README.rst` line 16 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFicyAQ5Xw8DojzBSva:-NFicyAQ5Xw8DojzBSvb:b-xd3awe) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/README.rst#L16)):*
> ```reStructuredText
> for userspace programs to use the new IOCTLs. Do it manually:
> 
>     sudo cp gramine_test_dev_ioctl.h /usr/local/include/
> ```

Oh no. Do we even need this? How do we plan to test that ioctls PR in CI (I forgot already)? Cant we just add a custom `-I` path?
This will break if we update the module and forget to copy this header.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @woju)

___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 4 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFibCok-9FitTl_EWmm:-NFigW-9Ai6ezVpU4Ka0:b-u7e884) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/gramine_test_dev_ioctl.h#L4)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We need this header also in userspace.
</blockquote></details>

Is this true? We use `#include <sys/ioctl.h>` in our userspace program (https://github.com/gramineproject/gramine/pull/671/files#diff-f183e22ffcfde641d8ac6d3c9083eecee3d3981653502f9f0381b08b4bfe7f9d).

And afaik, `sys/ioctl.h` is used for Glibc-based programs, and `linux/ioctl.h` is used for close-to-kernel programs/kernel modules. Is this wrong? See https://unix.stackexchange.com/questions/7928/difference-between-usr-include-sys-and-usr-include-linux
___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 6 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFibGXUAnuZz7jhGK2g:-NFihyv65h7JlBCsHsqI:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/gramine_test_dev_ioctl.h#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please wrap in `ifndef`
</blockquote></details>

Done.
___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 7 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFibK9XEutX3ItJPAu_:-NFiiS9t4aUKIsArJY5Y:b-896fix) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/gramine_test_dev_ioctl.h#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`typedef` or better `include <sys/types.h>`
</blockquote></details>

Done.
___
*[`gramine-device-testing-module/README.rst` line 16 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFicyAQ5Xw8DojzBSva:-NFikDCa4Y-EhJIoOoh9:bofqr39) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/README.rst#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Oh no. Do we even need this? How do we plan to test that ioctls PR in CI (I forgot already)? Cant we just add a custom `-I` path?
This will break if we update the module and forget to copy this header.
</blockquote></details>

We wanted to test it in a bare-metal Docker container. In this Docker container, we will git-clone Gramine and git-clone this `device-testing-tools` repo, then build Gramine + build this kernel module. Then we install the kernel module + perform this copy of the header. Finally, we create a bare-bones VM inside this Docker container and share the complete Docker-container FS with the VM in read-only mode (via `virtio-fs` driver). So all files, including all files under `/usr/local/include/` will be visible inside a VM.

In the corresponding core-Gramine PR, I have this: https://github.com/gramineproject/gramine/pull/671/files#diff-629d4997b684f0eed5f9d0e53d452f70fa26645f0f74a666650c81a77045d952

But no problem, I can copy this header file wherever, or I can just point to this file directly (we just need to agree on the FS hierarchy inside the testing Docker image). Just tell me which option you prefer.

(And yes, we're missing the Dockerfile for the Jenkins CI at this point, so things are a bit "blurry". Pinging @woju again to set up a bare-metal Ubuntu 22.04 machine in CI :))

**Review by boryspoplawski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 4 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFibCok-9FitTl_EWmm:-NFizJkW8Slyn0jwbhwv:bpat4hx) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/gramine_test_dev_ioctl.h#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this true? We use `#include <sys/ioctl.h>` in our userspace program (https://github.com/gramineproject/gramine/pull/671/files#diff-f183e22ffcfde641d8ac6d3c9083eecee3d3981653502f9f0381b08b4bfe7f9d).

And afaik, `sys/ioctl.h` is used for Glibc-based programs, and `linux/ioctl.h` is used for close-to-kernel programs/kernel modules. Is this wrong? See https://unix.stackexchange.com/questions/7928/difference-between-usr-include-sys-and-usr-include-linux
</blockquote></details>

This file uses stuff exported by either of these 2 headers, so it always needs to include one (currently it's only included for kernel compilation). You can either `ifdef__KERNEL__` or just include `linux/ioctl.h` and not bother.
___
*[`gramine-device-testing-module/README.rst` line 16 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFicyAQ5Xw8DojzBSva:-NFj-u6L5Gtsk0iQRER8:b-my49xv) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/README.rst#L16)):*
> We wanted to test it in a bare-metal Docker container.

Why bare-metal? Nested virt should work too. Why docker? It doesn't matter for us I think (in the end we probably use it anyway, but it's not a requirement).

> In this Docker container, we will git-clone Gramine and git-clone this device-testing-tools repo, then build Gramine + build this kernel module. Then we install the kernel module + perform this copy of the header. Finally, we create a bare-bones VM inside this Docker container and share the complete Docker-container FS with the VM in read-only mode (via virtio-fs driver). So all files, including all files under /usr/local/include/ will be visible inside a VM.

Why? Why not compile this inside VM?

Also, I would remove this from README and add to `make install` target

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: 4 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 4 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFibCok-9FitTl_EWmm:-NFx5oiF896ncqZfZf3S:boqfaz6) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/gramine_test_dev_ioctl.h#L4)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file uses stuff exported by either of these 2 headers, so it always needs to include one (currently it's only included for kernel compilation). You can either `ifdef__KERNEL__` or just include `linux/ioctl.h` and not bother.
</blockquote></details>

Done. I am not supposed to use `linux/ioctl.h` in userspace programs. Also see https://unix.stackexchange.com/questions/701230/is-there-any-difference-between-include-linux-ioctl-h-and-include-sys-ioctl.
___
*[`gramine-device-testing-module/README.rst` line 16 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFicyAQ5Xw8DojzBSva:-NFx7SV46q59GCoS1eKN:bn228wd) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/README.rst#L16)):*
> Also, I would remove this from README and add to make install target

Done.

> Why bare-metal? Nested virt should work too. Why docker? It doesn't matter for us I think (in the end we probably use it anyway, but it's not a requirement).

There was some reason to require bare-metal... SGX doesn't work in nested virtualization? Something like this. If you'll insist, I can dig and figure out whether nested virtualization is possible...

> Why? Why not compile this inside VM?

Well, that's how we decided to do it in this repo: https://github.com/gramineproject/device-testing-tools#initramfs-builder. You wrote that yourself. Or am I missing something?

**Review by boryspoplawski — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`gramine-device-testing-module/gramine_test_dev_ioctl.h` line 4 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFibCok-9FitTl_EWmm:-NFxp-AACjzyrVI8gNWe:b42mvwc) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/gramine_test_dev_ioctl.h#L4)):*
> I am not supposed to use linux/ioctl.h in userspace programs. 

Because a random guy on the internet said so, without giving **any** arguments?

In this file it would be fine as it does not need `ioctl` definition, only `_IO**` macros.
___
*[`gramine-device-testing-module/README.rst` line 16 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFicyAQ5Xw8DojzBSva:-NFxqK2p5N69F57g6AFl:b62tghr) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/README.rst#L16)):*
> Well, that's how we decided to do it in this repo: https://github.com/gramineproject/device-testing-tools#initramfs-builder. You wrote that yourself. Or am I missing something?

That script doesn't build the testing module (only initramfs), does it?

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`gramine-device-testing-module/README.rst` line 16 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFicyAQ5Xw8DojzBSva:-NGGAzZm6y4u7tBz8PkN:bq8nuz5) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/README.rst#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Well, that's how we decided to do it in this repo: https://github.com/gramineproject/device-testing-tools#initramfs-builder. You wrote that yourself. Or am I missing something?

That script doesn't build the testing module (only initramfs), does it?
</blockquote></details>

Yes. Sorry, I got lost in your arguments, I'm not sure what's the real question here. Anyway, you approved, so I'll proceed with merging :)

**Review by boryspoplawski — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/device-testing-tools/3)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`gramine-device-testing-module/README.rst` line 16 at r2](https://reviewable.io/reviews/gramineproject/device-testing-tools/3#-NFicyAQ5Xw8DojzBSva:-NGGxjaeCVKxEVD9nbOw:b-qxh6pt) ([raw file](https://github.com/gramineproject/device-testing-tools/blob/cc8b1bd1d440adca1cf69a3b2e8d0ab23e5e703b/gramine-device-testing-module/README.rst#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes. Sorry, I got lost in your arguments, I'm not sure what's the real question here. Anyway, you approved, so I'll proceed with merging :)
</blockquote></details>

These were orthogonal to this PR, so we can discuss it on the CI pipeline PR, once it's submitted

**Pull request merged**
